#!/bin/bash
#SBATCH --job-name=genespace_liftover
#SBATCH --output=slurm_output/%x_%j.out
#SBATCH --error=slurm_output/%x_%j.err
#SBATCH --time=4:00:00
#SBATCH --cpus-per-task=16
#SBATCH --mem=20G
#SBATCH --mail-type=ALL
#SBATCH --gres=lscratch:500

set -euo pipefail

REF="${1:?Usage: $0 <REF_GENOME>}"
SPECIES="${2:?Usage: $0 <SPECIES>}"
PROJDIR="${3:?Usage: $0 <PROJ_DIR>}"

SCRIPT=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/analyses/Genespace/scripts/1c_genespace.wholegenome.r

OUTDIR=${PROJDIR}/plots
export WORKING_DIR=${PROJDIR}/${SPECIES}

mkdir -p $OUTDIR

source myconda
mamba activate genespace_py3.10

echo "Running ${SPECIES} "

Rscript "${SCRIPT}" "${SPECIES}" "${OUTDIR}/" "${REF}"

# Reduce file number generated by genespace

r="${WORKING_DIR}/orthofinder"
out="${r}.tar.gz"
if [ -d "${r}" ]; then
    tar -C "$(dirname "$r")" -cf - "$(basename "$r")" | bgzip -c > "$out" && rm -rf "$r"
fi
