#!/bin/bash
#SBATCH --job-name=genespace_liftover
#SBATCH --output=slurm_output/%x_%A_%a.out
#SBATCH --error=slurm_output/%x_%A_%a.err
#SBATCH --time=4:00:00
#SBATCH --cpus-per-task=16
#SBATCH --mem=20G
#SBATCH --mail-type=ALL
#SBATCH --gres=lscratch:500

set -euo pipefail

REF="${1:?Usage: $0 <REF_GENOME>}"

PAIRFILE=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/referencelists/species.sexchr.for_genespace_array.lifted.squamates_VGP.csv
SCRIPT=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/analyses/Genespace/scripts/1c_genespace.wholegenome.largegaps.r
SEXCHRSCRIPT=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/analyses/Genespace/scripts/1d_genespace.wholegenome.sexchr.lifted.r
OUTDIR=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/analyses/Genespace/${REF}/sexshared_plots/

# Grab the Nth line from the pairfile: "Species SexChr"
line=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${PAIRFILE}")
SPECIES=$(awk '{print $1}' <<< "${line}")
SEXCHR=$(awk '{print $2}' <<< "${line}")
WORKDIR=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/analyses/Genespace/${REF}/sexshared_squamates_VGP/${SPECIES}

if [ -z "${line}" ]; then
    echo "No line found for SLURM_ARRAY_TASK_ID=${SLURM_ARRAY_TASK_ID} in ${PAIRFILE}" >&2
    exit 1
fi

if [ -z "${SPECIES}" ] || [ -z "${SEXCHR}" ]; then
    echo "Could not parse species/sex chromosome from line: ${line}" >&2
    exit 1
fi

if [ ! -d "${WORKDIR}" ]; then
    echo "Skipping ${SPECIES}: missing directory ${WORKDIR}" >&2
    exit 0
fi

export WORKING_DIR="${WORKDIR}"
export OMP_NUM_THREADS="${SLURM_CPUS_PER_TASK}"

mkdir -p "${OUTDIR}" slurm_output
cd "${OUTDIR}"

source myconda
mamba activate genespace_py3.10

echo "Running ${SPECIES} (sex chromosome: ${SEXCHR})"

Rscript "${SCRIPT}" "${SPECIES}" "${OUTDIR}/" "${REF}"

# Reduce file number generated by genespace
shopt -s nullglob

r="${WORKDIR}/orthofinder"
out="${r}.tar.gz"
if [ -d "${r}" ]; then
    tar -C "$(dirname "$r")" -cf - "$(basename "$r")" | bgzip -c > "$out" && rm -rf "$r"
fi

# Plot only synteny with a sex chromosome in the query genome
Rscript "${SEXCHRSCRIPT}" "${SPECIES}" "${WORKDIR}/" "${SEXCHR}" "${REF}"