#!/bin/bash
#SBATCH --job-name=genespace
#SBATCH --output=slurm_output/%x_%A_%a.out
#SBATCH --error=slurm_output/%x_%A_%a.err
#SBATCH --time=10:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=20G
#SBATCH --mail-type=ALL
#SBATCH --gres=lscratch:500

set -euo pipefail

REF="${1:?Usage: $0 <REF_GENOME>}"

PAIRFILE=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/referencelists/species.sexchr.for_genespace_array.troubleshoot.csv
SCRIPT=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/analyses/Genespace/scripts/1c_genespace.wholegenome.r
SEXCHRSCRIPT=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/analyses/Genespace/scripts/1d_genespace.wholegenome.sexchr.r
OUTDIR=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/analyses/Genespace/${REF}/sexshared_plots/

# Grab the Nth line (array index) and parse "Species Chromosome"
line=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${PAIRFILE}")
SPECIES=$(awk '{print $1}' <<< "${line}")
SEXCHR=$(awk '{print $2}' <<< "${line}")
WORKDIR=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/analyses/Genespace/${REF}/sexshared/${SPECIES}

export WORKING_DIR="${WORKDIR}"
export OMP_NUM_THREADS="${SLURM_CPUS_PER_TASK}"
mkdir -p "${OUTDIR}"
cd "${OUTDIR}"

source myconda
mamba activate genespace_py3.10

Rscript "${SCRIPT}" "${SPECIES}" "${OUTDIR}/" "${REF}"

# Reduce file number generated by genespace
# make globs that match nothing expand to nothing
shopt -s nullglob

# tar+bgzip each Orthogroup_Sequences dir, then delete it

r="${WORKDIR}"/orthofinder
out="${r}.tar.gz"
tar -C "$(dirname "$r")" -cf - "$(basename "$r")" | bgzip -c > "$out" && rm -rf "$r"


# Plot only synteny with a sex chromosome in the query genome
Rscript "${SEXCHRSCRIPT}" "${SPECIES}" "${WORKDIR}/" "${SEXCHR}" "${REF}"
