#!/bin/bash
#SBATCH --job-name=gs_chicken_wg
#SBATCH --output=slurm_output/%x_%A_%a.out
#SBATCH --error=slurm_output/%x_%A_%a.err
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=16
#SBATCH --mem=20G
#SBATCH --mail-type=ALL
#SBATCH --gres=lscratch:500

set -euo pipefail

SLURM_ARRAY_TASK_ID=115
PAIRFILE=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/referencelists/species.sexchr.for_genespace_array.csv
SCRIPT=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/analyses/Genespace/XZ_Synteny_Gallus_gallus/scripts/genespace.synteny_to_chicken.wholegenome.r
OUTDIR=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/analyses/Genespace/XZ_Synteny_Gallus_gallus/all/plots

# Grab the Nth line (array index) and parse "Species Chromosome"
line=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${PAIRFILE}")
SPECIES=$(awk '{print $1}' <<< "${line}")
WORKDIR=/data/Wilson_Lab/projects/VGP_Phase_1_Sex_Chr_Project/jacksondan/analyses/Genespace/XZ_Synteny_Gallus_gallus/all/genespace/${SPECIES}

export WORKING_DIR="${WORKDIR}"

cd "${OUTDIR}"

source myconda
mamba activate genespace

Rscript "${SCRIPT}" "${SPECIES}" "${OUTDIR}/"

# Reduce file number generated by genespace
# make globs that match nothing expand to nothing
shopt -s nullglob

# tar+bgzip each Orthogroup_Sequences dir, then delete it
for r in "${WORKDIR}"/orthofinder/Results*/Orthogroup_Sequences; do
  [ -d "$r" ] || continue
  out="${r%/}.tar.gz"
  tar -C "$(dirname "$r")" -cf - "$(basename "$r")" | bgzip -c > "$out" && rm -rf "$r"
done

# 2) One combined tar+bgzip of ALL Single_Copy_Orthologue_Sequences (across Results*), written to ${OUTDIR}/${SPECIES}/
for r in "${WORKDIR}"/orthofinder/Results*/Single_Copy_Orthologue_Sequences; do
  [ -d "$r" ] || continue
  out="${r%/}.tar.gz"
  tar -C "$(dirname "$r")" -cf - "$(basename "$r")" | bgzip -c > "$out" && rm -rf "$r"
done